_BASE_: "../../../configs/Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: "BorderMaskROIHeads"
    IN_FEATURES: [ "p2", "p3", "p4", "p5" ]
  ROI_MASK_HEAD:
    NAME: "BorderMaskRCNNConvUpsampleHeadV2"
  BORDER_HEAD:
    NAME: "ParallelBorderHead"
    POINTS_NUM: 50
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.005
  STEPS: (6000, 8000)
  MAX_ITER: 10000
OUTPUT_DIR: "./output_v4_10000"
DATASETS:
  TRAIN: ("endocv_2020_train",)
  TEST: ("endocv_2020_val",)