_BASE_: "../../../../configs/Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NAME: "BorderMaskROIHeads"
    IN_FEATURES: [ "p2", "p3", "p4", "p5" ]
    NUM_CLASSES: 1
  ROI_MASK_HEAD:
    NAME: "BorderMaskRCNNConvUpsampleHeadV2"
  BORDER_HEAD:
    NAME: "ParallelBorderHead"
    POINTS_NUM: 50
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.005
  STEPS: (6000, 8000)
  MAX_ITER: 10000
OUTPUT_DIR: "./polyp/bordermask_LOG_R_101_FPN_aug_class1/"
DATASETS:
  TRAIN: ("ETIS_train",)
  TEST: ("ETIS_val",)
INPUT:
  AUG: True
  BLUR:
    ENABLED: True
    Prob: 0.5
    KERNEL_SIZE: 3