_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.005
  STEPS: (6000, 8000)
  MAX_ITER: 10000
DATASETS:
  TRAIN: ("ETIS_train",)
  TEST: ("Kvasir_val",)
OUTPUT_DIR: "./polyp_eval/mask_rcnn_R_101_FPN_1x/Kvasir_val"
