_BASE_: "../../../../configs/Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NAME: "BorderMaskROIHeads"
    IN_FEATURES: [ "p2", "p3", "p4", "p5" ]
    NUM_CLASSES: 1
  ROI_MASK_HEAD:
    NAME: "BorderMaskRCNNConvUpsampleHeadV2"
    LEARNABLE_BOUNDARY : True
  BORDER_HEAD:
    NAME: "ParallelBorderHead"
    POINTS_NUM: 50
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.005
  STEPS: (6000, 8000)
  MAX_ITER: 10000
OUTPUT_DIR: "./polyp/final/bordermask_LOG_R_101_FPN_aug_class1_mstrain/"
DATASETS:
  TRAIN: ("ETIS_train",)
  TEST: ("CVC_ClinicDB_val", "ETIS_val", "Kvasir_val", "CVC_ColonDB_val","CVC_300_val")
INPUT:
  MIN_SIZE_TRAIN: (320, 360, 420, 480, 560, 600, 640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 800
  AUG: True
  BLUR:
    ENABLED: True
    Prob: 0.5
    KERNEL_SIZE: 3